services:
  - type: web
    name: photo-ai
    dockerfilePath: Dockerfile
    dockerContext: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health
    plan: free
